using System.Collections.Generic;
using SportRadar.Common.Windows;

namespace SportRadar.DAL.CommonObjects
{
    public sealed class TableSpecification
    {
        public TableSpecification(string sTableName, bool bIsAutoGeneratedIdentity, params string[] argIdentityNames)
        {
            ExcpHelper.ThrowIf(string.IsNullOrEmpty(sTableName), "Table Name is empty");
            ExcpHelper.ThrowIf(argIdentityNames == null, "Identity Names are not specified");

            this.TableName = sTableName;
            this.IsAutoGeneratedIdentity = bIsAutoGeneratedIdentity;
            this.IdentityNames = new List<string>(argIdentityNames);
            this.IdentityNames = this.IdentityNames.ConvertAll(s => s.ToLowerInvariant());
        }

        public string TableName { get; private set; }
        public bool IsAutoGeneratedIdentity { get; private set; }
        public List<string> IdentityNames { get; private set; }
    }
}